name: openwrt-toolchain

on: workflow_dispatch

jobs:
  build:
    name: openwrt-x86_64-musl
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        version:
          - gcc14
          - gcc15
          - gcc16
          
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Show system
      run: |
        lscpu
        free -h
        df -Th
        uname -a

    - name: Set release env
      run: |
        sudo mkdir -p /builder
        sudo chown -R runner.runner /builder
        echo WORKDIR="/builder" >> "$GITHUB_ENV"
        git config --global user.name 'actions'
        git config --global user.email 'action@github.com'

    - name: Free disk space
      uses: MomoFlora/actions@free-disk
      with:
        build-mount-path: /builder

    - name: Build System Setup
      uses: MomoFlora/actions@openwrt-build-setup

    - name: Install LLVM
      uses: MomoFlora/actions@install-llvm

    - name: Compile Toolchain
      working-directory: /builder
      env:
        git_name: MomoFlora
        git_password: ${{ secrets.git_password }}
      run: |
        if [ "${{ matrix.version }}" = "gcc14" ]; then
          export USE_GCC14=y
        elif [ "${{ matrix.version }}" = "gcc15" ]; then
          export USE_GCC15=y
        elif [ "${{ matrix.version }}" = "gcc16" ]; then
          export USE_GCC16=y
        fi
        BUILD_TOOLCHAIN=y ENABLE_LTO=y ENABLE_BPF=y ENABLE_MOLD=y bash <(curl -sS ${{ secrets.script_url_general }}) openwrt-25.12 x86_64

    - name: Create release
      uses: ncipollo/release-action@v1.14.0
      with:
        name: openwrt-25.12
        allowUpdates: true
        tag: openwrt-25.12
        commit: openwrt-25.12
        replacesArtifacts: true
        token: ${{ secrets.workflow_token }}
        artifacts: ${{ env.WORKDIR }}/openwrt/toolchain-cache/*
